name: first

on: [push]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: date
    
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: date

  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step 1
        run: date

  job4:
    name: Forth job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Step 1
        run: date
